/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_impl_dae_fun_jac_x_xdot_u_z_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[59] = 
  {13, 13, 0, 0, 0, 0, 1, 2,
  3, 8, 14, 20, 25, 31, 37, 43,
  0, 1, 2, 3, 4, 7, 8, 9,
  3, 4, 5, 6, 8, 9, 3, 4,
  5, 6, 7, 9, 3, 4, 6, 7,
  8, 6, 7, 8, 9, 11, 12, 6,
  7, 8, 9, 10, 12, 6, 7, 8,
  9, 10, 11};
static const casadi_int casadi_s5[29] = 
  {13, 13, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11, 12, 13,
  0, 1, 2, 3, 4, 5, 6, 7,
  8, 9, 10, 11, 12};
static const casadi_int casadi_s6[13] = 
  {13, 4, 0, 3, 4, 5, 6, 3,
  4, 5, 10, 11, 12};
static const casadi_int casadi_s7[3] = {13, 0, 1};

/* quadrotor_impl_dae_fun_jac_x_xdot_u_z:(i0[13],i1[13],i2[4],i3[0],i4[],i5[0])->(o0[13],o1[13x13,43nz],o2[13x13,13nz],o3[13x4,6nz],o4[13x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21, a22, a23;
  casadi_real a24, a25, a26, a27, a28, a29;
  a00=arg[1]? arg[1][0] : 0;
  a01=arg[0]? arg[0][3] : 0;
  a00=(a00-a01);
  if (res[0]!=0) res[0][0]=a00;
  a00=arg[1]? arg[1][1] : 0;
  a01=arg[0]? arg[0][4] : 0;
  a00=(a00-a01);
  if (res[0]!=0) res[0][1]=a00;
  a00=arg[1]? arg[1][2] : 0;
  a01=arg[0]? arg[0][5] : 0;
  a00=(a00-a01);
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[1]? arg[1][3] : 0;
  a01=3.7037037037037038e+01;
  a02=2.;
  a03=arg[0]? arg[0][7] : 0;
  a04=arg[0]? arg[0][9] : 0;
  a05=(a03*a04);
  a06=arg[0]? arg[0][6] : 0;
  a07=arg[0]? arg[0][8] : 0;
  a08=(a06*a07);
  a05=(a05+a08);
  a05=(a02*a05);
  a05=(a01*a05);
  a08=arg[2]? arg[2][0] : 0;
  a09=(a05*a08);
  a00=(a00-a09);
  if (res[0]!=0) res[0][3]=a00;
  a00=arg[1]? arg[1][4] : 0;
  a09=(a07*a04);
  a10=(a06*a03);
  a09=(a09-a10);
  a09=(a02*a09);
  a09=(a01*a09);
  a10=(a09*a08);
  a00=(a00-a10);
  if (res[0]!=0) res[0][4]=a00;
  a00=arg[1]? arg[1][5] : 0;
  a10=-9.8100000000000005e+00;
  a11=1.;
  a12=casadi_sq(a03);
  a13=casadi_sq(a07);
  a12=(a12+a13);
  a12=(a02*a12);
  a12=(a11-a12);
  a12=(a01*a12);
  a13=(a12*a08);
  a10=(a10+a13);
  a00=(a00-a10);
  if (res[0]!=0) res[0][5]=a00;
  a00=arg[1]? arg[1][6] : 0;
  a10=5.0000000000000000e-01;
  a13=arg[0]? arg[0][10] : 0;
  a14=(a10*a13);
  a15=(a14*a03);
  a16=arg[0]? arg[0][11] : 0;
  a17=(a10*a16);
  a18=(a17*a07);
  a15=(a15+a18);
  a18=arg[0]? arg[0][12] : 0;
  a19=(a10*a18);
  a20=(a19*a04);
  a15=(a15+a20);
  a00=(a00+a15);
  if (res[0]!=0) res[0][6]=a00;
  a00=arg[1]? arg[1][7] : 0;
  a15=(a14*a06);
  a20=(a19*a07);
  a15=(a15+a20);
  a20=(a17*a04);
  a15=(a15-a20);
  a00=(a00-a15);
  if (res[0]!=0) res[0][7]=a00;
  a00=arg[1]? arg[1][8] : 0;
  a15=(a17*a06);
  a20=(a19*a03);
  a15=(a15-a20);
  a20=(a14*a04);
  a15=(a15+a20);
  a00=(a00-a15);
  if (res[0]!=0) res[0][8]=a00;
  a00=arg[1]? arg[1][9] : 0;
  a15=(a19*a06);
  a20=(a17*a03);
  a15=(a15+a20);
  a20=(a14*a07);
  a15=(a15-a20);
  a00=(a00-a15);
  if (res[0]!=0) res[0][9]=a00;
  a00=arg[1]? arg[1][10] : 0;
  a15=7.1428571428571435e+04;
  a20=arg[2]? arg[2][1] : 0;
  a20=(a15*a20);
  a21=2.1699999999999999e-05;
  a22=(a15*a16);
  a22=(a21*a22);
  a23=(a22*a18);
  a24=(a18*a16);
  a23=(a23-a24);
  a20=(a20-a23);
  a00=(a00-a20);
  if (res[0]!=0) res[0][10]=a00;
  a00=arg[1]? arg[1][11] : 0;
  a20=arg[2]? arg[2][2] : 0;
  a20=(a15*a20);
  a23=(a18*a13);
  a15=(a15*a13);
  a21=(a21*a15);
  a15=(a21*a18);
  a23=(a23+a15);
  a20=(a20-a23);
  a00=(a00-a20);
  if (res[0]!=0) res[0][11]=a00;
  a00=arg[1]? arg[1][12] : 0;
  a20=4.6082949308755764e+04;
  a23=arg[2]? arg[2][3] : 0;
  a23=(a20*a23);
  a15=1.4000000000000000e-05;
  a24=(a20*a13);
  a24=(a15*a24);
  a25=(a24*a16);
  a20=(a20*a16);
  a15=(a15*a20);
  a20=(a15*a13);
  a25=(a25-a20);
  a23=(a23-a25);
  a00=(a00-a23);
  if (res[0]!=0) res[0][12]=a00;
  a00=-1.;
  if (res[1]!=0) res[1][0]=a00;
  if (res[1]!=0) res[1][1]=a00;
  if (res[1]!=0) res[1][2]=a00;
  a00=(a02*a07);
  a00=(a01*a00);
  a00=(a08*a00);
  a00=(-a00);
  if (res[1]!=0) res[1][3]=a00;
  a23=(a02*a03);
  a23=(a01*a23);
  a23=(a08*a23);
  if (res[1]!=0) res[1][4]=a23;
  a25=(-a14);
  if (res[1]!=0) res[1][5]=a25;
  a20=(-a17);
  if (res[1]!=0) res[1][6]=a20;
  a26=(-a19);
  if (res[1]!=0) res[1][7]=a26;
  a27=(a02*a04);
  a27=(a01*a27);
  a27=(a08*a27);
  a27=(-a27);
  if (res[1]!=0) res[1][8]=a27;
  a28=(a02*a06);
  a28=(a01*a28);
  a28=(a08*a28);
  if (res[1]!=0) res[1][9]=a28;
  a29=(a03+a03);
  a29=(a02*a29);
  a29=(a01*a29);
  a29=(a08*a29);
  if (res[1]!=0) res[1][10]=a29;
  if (res[1]!=0) res[1][11]=a14;
  if (res[1]!=0) res[1][12]=a19;
  if (res[1]!=0) res[1][13]=a20;
  a28=(-a28);
  if (res[1]!=0) res[1][14]=a28;
  if (res[1]!=0) res[1][15]=a27;
  a27=(a07+a07);
  a02=(a02*a27);
  a01=(a01*a02);
  a08=(a08*a01);
  if (res[1]!=0) res[1][16]=a08;
  if (res[1]!=0) res[1][17]=a17;
  if (res[1]!=0) res[1][18]=a26;
  if (res[1]!=0) res[1][19]=a14;
  a23=(-a23);
  if (res[1]!=0) res[1][20]=a23;
  if (res[1]!=0) res[1][21]=a00;
  if (res[1]!=0) res[1][22]=a19;
  if (res[1]!=0) res[1][23]=a17;
  if (res[1]!=0) res[1][24]=a25;
  a03=(a10*a03);
  if (res[1]!=0) res[1][25]=a03;
  a06=(a10*a06);
  a06=(-a06);
  if (res[1]!=0) res[1][26]=a06;
  a04=(a10*a04);
  a25=(-a04);
  if (res[1]!=0) res[1][27]=a25;
  a10=(a10*a07);
  if (res[1]!=0) res[1][28]=a10;
  a07=1.5500000000000000e+00;
  a07=(a07*a18);
  a25=(a18+a07);
  if (res[1]!=0) res[1][29]=a25;
  a25=6.4516129032258074e-01;
  a17=(a25*a16);
  a17=(a17-a15);
  if (res[1]!=0) res[1][30]=a17;
  if (res[1]!=0) res[1][31]=a10;
  if (res[1]!=0) res[1][32]=a04;
  if (res[1]!=0) res[1][33]=a06;
  a17=(-a03);
  if (res[1]!=0) res[1][34]=a17;
  a07=(a07-a18);
  if (res[1]!=0) res[1][35]=a07;
  a25=(a25*a13);
  a24=(a24-a25);
  if (res[1]!=0) res[1][36]=a24;
  if (res[1]!=0) res[1][37]=a04;
  a10=(-a10);
  if (res[1]!=0) res[1][38]=a10;
  if (res[1]!=0) res[1][39]=a03;
  if (res[1]!=0) res[1][40]=a06;
  a22=(a22-a16);
  if (res[1]!=0) res[1][41]=a22;
  a13=(a13+a21);
  if (res[1]!=0) res[1][42]=a13;
  if (res[2]!=0) res[2][0]=a11;
  if (res[2]!=0) res[2][1]=a11;
  if (res[2]!=0) res[2][2]=a11;
  if (res[2]!=0) res[2][3]=a11;
  if (res[2]!=0) res[2][4]=a11;
  if (res[2]!=0) res[2][5]=a11;
  if (res[2]!=0) res[2][6]=a11;
  if (res[2]!=0) res[2][7]=a11;
  if (res[2]!=0) res[2][8]=a11;
  if (res[2]!=0) res[2][9]=a11;
  if (res[2]!=0) res[2][10]=a11;
  if (res[2]!=0) res[2][11]=a11;
  if (res[2]!=0) res[2][12]=a11;
  a05=(-a05);
  if (res[3]!=0) res[3][0]=a05;
  a09=(-a09);
  if (res[3]!=0) res[3][1]=a09;
  a12=(-a12);
  if (res[3]!=0) res[3][2]=a12;
  a12=-7.1428571428571435e+04;
  if (res[3]!=0) res[3][3]=a12;
  if (res[3]!=0) res[3][4]=a12;
  a12=-4.6082949308755764e+04;
  if (res[3]!=0) res[3][5]=a12;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_fun_jac_x_xdot_u_z(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_fun_jac_x_xdot_u_z_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_fun_jac_x_xdot_u_z_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_impl_dae_fun_jac_x_xdot_u_z_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_fun_jac_x_xdot_u_z_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_impl_dae_fun_jac_x_xdot_u_z_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_impl_dae_fun_jac_x_xdot_u_z_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_impl_dae_fun_jac_x_xdot_u_z_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_impl_dae_fun_jac_x_xdot_u_z_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_impl_dae_fun_jac_x_xdot_u_z_n_out(void) { return 5;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_impl_dae_fun_jac_x_xdot_u_z_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_impl_dae_fun_jac_x_xdot_u_z_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_impl_dae_fun_jac_x_xdot_u_z_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    case 4: return "o4";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_impl_dae_fun_jac_x_xdot_u_z_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    case 5: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_impl_dae_fun_jac_x_xdot_u_z_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s4;
    case 2: return casadi_s5;
    case 3: return casadi_s6;
    case 4: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_fun_jac_x_xdot_u_z_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_fun_jac_x_xdot_u_z_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
