/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) quadrotor_impl_dae_jac_x_xdot_u_z_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {4, 1, 1};
static const casadi_int casadi_s2[3] = {0, 1, 1};
static const casadi_int casadi_s3[3] = {0, 0, 1};
static const casadi_int casadi_s4[59] = 
  {13, 13, 0, 0, 0, 0, 1, 2,
  3, 8, 14, 20, 25, 31, 37, 43,
  0, 1, 2, 3, 4, 7, 8, 9,
  3, 4, 5, 6, 8, 9, 3, 4,
  5, 6, 7, 9, 3, 4, 6, 7,
  8, 6, 7, 8, 9, 11, 12, 6,
  7, 8, 9, 10, 12, 6, 7, 8,
  9, 10, 11};
static const casadi_int casadi_s5[29] = 
  {13, 13, 0, 1, 2, 3, 4, 5,
  6, 7, 8, 9, 10, 11, 12, 13,
  0, 1, 2, 3, 4, 5, 6, 7,
  8, 9, 10, 11, 12};
static const casadi_int casadi_s6[13] = 
  {13, 4, 0, 3, 4, 5, 6, 3,
  4, 5, 10, 11, 12};
static const casadi_int casadi_s7[3] = {13, 0, 1};

/* quadrotor_impl_dae_jac_x_xdot_u_z:(i0[13],i1[13],i2[4],i3[0],i4[],i5[0])->(o0[13x13,43nz],o1[13x13,13nz],o2[13x4,6nz],o3[13x0]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a00, a01, a02, a03, a04, a05, a06, a07, a08, a09, a10, a11;
  casadi_real a12, a13, a14, a15, a16, a17, a18, a19, a20, a21;
  a00=-1.;
  if (res[0]!=0) res[0][0]=a00;
  if (res[0]!=0) res[0][1]=a00;
  if (res[0]!=0) res[0][2]=a00;
  a00=arg[2]? arg[2][0] : 0;
  a01=3.7037037037037038e+01;
  a02=2.;
  a03=arg[0]? arg[0][8] : 0;
  a04=(a02*a03);
  a04=(a01*a04);
  a04=(a00*a04);
  a04=(-a04);
  if (res[0]!=0) res[0][3]=a04;
  a05=arg[0]? arg[0][7] : 0;
  a06=(a02*a05);
  a06=(a01*a06);
  a06=(a00*a06);
  if (res[0]!=0) res[0][4]=a06;
  a07=5.0000000000000000e-01;
  a08=arg[0]? arg[0][10] : 0;
  a09=(a07*a08);
  a10=(-a09);
  if (res[0]!=0) res[0][5]=a10;
  a11=arg[0]? arg[0][11] : 0;
  a12=(a07*a11);
  a13=(-a12);
  if (res[0]!=0) res[0][6]=a13;
  a14=arg[0]? arg[0][12] : 0;
  a15=(a07*a14);
  a16=(-a15);
  if (res[0]!=0) res[0][7]=a16;
  a17=arg[0]? arg[0][9] : 0;
  a18=(a02*a17);
  a18=(a01*a18);
  a18=(a00*a18);
  a18=(-a18);
  if (res[0]!=0) res[0][8]=a18;
  a19=arg[0]? arg[0][6] : 0;
  a20=(a02*a19);
  a20=(a01*a20);
  a20=(a00*a20);
  if (res[0]!=0) res[0][9]=a20;
  a21=(a05+a05);
  a21=(a02*a21);
  a21=(a01*a21);
  a21=(a00*a21);
  if (res[0]!=0) res[0][10]=a21;
  if (res[0]!=0) res[0][11]=a09;
  if (res[0]!=0) res[0][12]=a15;
  if (res[0]!=0) res[0][13]=a13;
  a20=(-a20);
  if (res[0]!=0) res[0][14]=a20;
  if (res[0]!=0) res[0][15]=a18;
  a18=(a03+a03);
  a18=(a02*a18);
  a18=(a01*a18);
  a00=(a00*a18);
  if (res[0]!=0) res[0][16]=a00;
  if (res[0]!=0) res[0][17]=a12;
  if (res[0]!=0) res[0][18]=a16;
  if (res[0]!=0) res[0][19]=a09;
  a06=(-a06);
  if (res[0]!=0) res[0][20]=a06;
  if (res[0]!=0) res[0][21]=a04;
  if (res[0]!=0) res[0][22]=a15;
  if (res[0]!=0) res[0][23]=a12;
  if (res[0]!=0) res[0][24]=a10;
  a10=(a07*a05);
  if (res[0]!=0) res[0][25]=a10;
  a12=(a07*a19);
  a12=(-a12);
  if (res[0]!=0) res[0][26]=a12;
  a15=(a07*a17);
  a04=(-a15);
  if (res[0]!=0) res[0][27]=a04;
  a07=(a07*a03);
  if (res[0]!=0) res[0][28]=a07;
  a04=1.5500000000000000e+00;
  a04=(a04*a14);
  a06=(a14+a04);
  if (res[0]!=0) res[0][29]=a06;
  a06=6.4516129032258063e-01;
  a09=(a06*a11);
  a16=1.3999999999999999e+00;
  a00=4.6082949308755761e-01;
  a18=(a00*a11);
  a18=(a16*a18);
  a09=(a09-a18);
  if (res[0]!=0) res[0][30]=a09;
  if (res[0]!=0) res[0][31]=a07;
  if (res[0]!=0) res[0][32]=a15;
  if (res[0]!=0) res[0][33]=a12;
  a09=(-a10);
  if (res[0]!=0) res[0][34]=a09;
  a04=(a04-a14);
  if (res[0]!=0) res[0][35]=a04;
  a00=(a00*a08);
  a16=(a16*a00);
  a06=(a06*a08);
  a16=(a16-a06);
  if (res[0]!=0) res[0][36]=a16;
  if (res[0]!=0) res[0][37]=a15;
  a07=(-a07);
  if (res[0]!=0) res[0][38]=a07;
  if (res[0]!=0) res[0][39]=a10;
  if (res[0]!=0) res[0][40]=a12;
  a12=2.1699999999999999e+00;
  a10=7.1428571428571430e-01;
  a07=(a10*a11);
  a07=(a12*a07);
  a07=(a07-a11);
  if (res[0]!=0) res[0][41]=a07;
  a10=(a10*a08);
  a12=(a12*a10);
  a08=(a08+a12);
  if (res[0]!=0) res[0][42]=a08;
  a08=1.;
  if (res[1]!=0) res[1][0]=a08;
  if (res[1]!=0) res[1][1]=a08;
  if (res[1]!=0) res[1][2]=a08;
  if (res[1]!=0) res[1][3]=a08;
  if (res[1]!=0) res[1][4]=a08;
  if (res[1]!=0) res[1][5]=a08;
  if (res[1]!=0) res[1][6]=a08;
  if (res[1]!=0) res[1][7]=a08;
  if (res[1]!=0) res[1][8]=a08;
  if (res[1]!=0) res[1][9]=a08;
  if (res[1]!=0) res[1][10]=a08;
  if (res[1]!=0) res[1][11]=a08;
  if (res[1]!=0) res[1][12]=a08;
  a12=(a05*a17);
  a10=(a19*a03);
  a12=(a12+a10);
  a12=(a02*a12);
  a12=(a01*a12);
  a12=(-a12);
  if (res[2]!=0) res[2][0]=a12;
  a17=(a03*a17);
  a19=(a19*a05);
  a17=(a17-a19);
  a17=(a02*a17);
  a17=(a01*a17);
  a17=(-a17);
  if (res[2]!=0) res[2][1]=a17;
  a05=casadi_sq(a05);
  a03=casadi_sq(a03);
  a05=(a05+a03);
  a02=(a02*a05);
  a08=(a08-a02);
  a01=(a01*a08);
  a01=(-a01);
  if (res[2]!=0) res[2][2]=a01;
  a01=-7.1428571428571430e-01;
  if (res[2]!=0) res[2][3]=a01;
  if (res[2]!=0) res[2][4]=a01;
  a01=-4.6082949308755761e-01;
  if (res[2]!=0) res[2][5]=a01;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_jac_x_xdot_u_z(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_jac_x_xdot_u_z_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_jac_x_xdot_u_z_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_impl_dae_jac_x_xdot_u_z_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_jac_x_xdot_u_z_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void quadrotor_impl_dae_jac_x_xdot_u_z_release(int mem) {
}

CASADI_SYMBOL_EXPORT void quadrotor_impl_dae_jac_x_xdot_u_z_incref(void) {
}

CASADI_SYMBOL_EXPORT void quadrotor_impl_dae_jac_x_xdot_u_z_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_impl_dae_jac_x_xdot_u_z_n_in(void) { return 6;}

CASADI_SYMBOL_EXPORT casadi_int quadrotor_impl_dae_jac_x_xdot_u_z_n_out(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_real quadrotor_impl_dae_jac_x_xdot_u_z_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_impl_dae_jac_x_xdot_u_z_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    case 4: return "i4";
    case 5: return "i5";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* quadrotor_impl_dae_jac_x_xdot_u_z_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    case 3: return "o3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_impl_dae_jac_x_xdot_u_z_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    case 4: return casadi_s3;
    case 5: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* quadrotor_impl_dae_jac_x_xdot_u_z_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    case 2: return casadi_s6;
    case 3: return casadi_s7;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_jac_x_xdot_u_z_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6;
  if (sz_res) *sz_res = 4;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

CASADI_SYMBOL_EXPORT int quadrotor_impl_dae_jac_x_xdot_u_z_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 6*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 4*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 0*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
